### ISSUE TITLE
error: use of undeclared identifier 'HUGE'

### ISSUE THREAD

**Issue by bperrenoud** [SINTEF-Geometry/GoTools#205]
I cant't build GoTools on my computer, it fails with error

> [...]/GoTools/sisl/src/crvarctang.c:174:19: error: use of undeclared identifier 'MAXDOUBLE'
>  tprev = (double)HUGE;
>                           ^
> [...]/GoTools/sisl/include/sislP.h:365:23: note: expanded from macro 'HUGE'
> #define HUGE          MAXDOUBLE
> [....]
> gotools-core/src/creators/ApproxSurf.C:306:29: error: use of undeclared identifier 'HUGE'

I guess that HUGE is define depending on platform. I'm running on Debian Testing. Here are some hardware info on my machine:

> system         20HH001SMZ (LENOVO_MT_20HH_BU_Think_FM_ThinkPad P51)
> bus            20HH001SMZ
> memory         32GiB System Memory
> memory         16GiB SODIMM DDR4 Synchronous Unbuffered (Unregistered) 2400 MHz (0.4 ns)
> memory         16GiB SODIMM DDR4 Synchronous Unbuffered (Unregistered) 2400 MHz (0.4 ns)
> memory         256KiB L1 cache
> memory         1MiB L2 cache
> memory         8MiB L3 cache
> processor      Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz
> memory         128KiB BIOS
> bridge         Intel Corporation
> bridge         Skylake PCIe Controller (x16)
> display        NVIDIA Corporation
> generic        Skylake Gaussian Mixture Model

**Comment by bperrenoud** [comment]
Hi. No worry.

I'm using clang version 5.0.0-+rc2-1

**Comment by sbriseid** [comment]
We do not support clang, but is should work nonetheless (I use it on my Mac).

It seems likely that the problem is related to values.h marked as obsolete (possibly missing on your system). One solution is to add __llvm__ or __clang__ to the sislP.h file (line 84) to define MAXDOUBLE, but that is just sidestepping. I guess we should define HUGE as std::numeric_limits<double>::max(). I'll update the issue once this is taken care of!

**Comment by fgfuchs** [comment]
I am getting the same error here all of a sudden, using both gcc 6.3 and 7.3

/usr/bin/c++   -I/.../gotools/gotools-core/include -I/.../gotools/newmat/include -I/.../gotools/sisl/include -I/.../gotools/ttl/include -o CMakeFiles/GoToolsCore.dir/src/creators/ApproxSurf.C.o -c /.../gotools/gotools-core/src/creators/ApproxSurf.C
/.../gotools/gotools-core/src/creators/ApproxSurf.C: In member function ‘int Go::ApproxSurf::get_min_deriv(std::shared_ptr<Go::SplineSurface>, double)’:
/.../gotools/gotools-core/src/creators/ApproxSurf.C:306:29: error: ‘HUGE’ was not declared in this scope
   double min_support_frac = HUGE;

**Comment by sbriseid** [comment]
This is not a bug. We do not support gcc above version 5, use gcc version 4.8, 4.9 or 5 and all is good.

Defining HUGE as described in my previous comment is not a solution as that project is pure c.

I guess we´ll eventually move on to newer gcc versions, I´ll look into the issue.

**Comment by sbriseid** [comment]
Did you read my previous comment? Does not play well with pure c (the sisl subproject).

We use Ubuntu LTS as reference distro, I´ll upgrade to 18.04 (gcc 7) in a couple of weeks.

**Comment by fgfuchs** [comment]
I am not sure what the issue is, it compiles on ubuntu with gcc7.3.0, but not on arch with gcc7.3.1. However, even if it is not a bug, it is better to use std::numeric_limits with max and lowest. I already created a pull request for it :smile:
